conversation/urls.py
from django.urls import path

from .import views

app_name = 'conversation'

urlpatterns = [
    path('' , views.inbox, name = 'inbox'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('new/<int:item_pk>/', views.new_conversation , name='new') ,
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from. import views 
from.forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('' ,views.index, name='index'),
    path ('contact/', views.contact, name = 'contact'),
    path ('aboutus/', views.aboutus, name = 'aboutus'),
    path('signup/',views.signup, name='signup'),
    path('logout/',views.logout_user, name='logout'),
    path('login/' , auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm) ,name='login'),
    path ('privacypolicy/', views.privacypolicy, name = 'privacypolicy'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('' ,views.index, name='index'),
    
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns= [
    path('',views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/delete/',views.delete, name='delete'),
    path('<int:pk>/edit/',views.edit, name='edit'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path ('', include ('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.forms import User

class LoginForm(AuthenticationForm):
    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Ваш логін',
        'class':'w-full py-4 px-6 rounded-xl'
    }))  
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Ваш пароль',
        'class':'w-full py-4 px-6 rounded-xl'
    }))  


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Ваш логін',
        'class':'w-full py-4 px-6 rounded-xl'
    }))    
    email=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Ваш email ',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password1=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Ваш пароль',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Повторити пароль',
        'class':'w-full py-4 px-6 rounded-xl'
    }))     

core/views.py
from django.contrib.auth import logout
from django.shortcuts import render,redirect

from item.models import Category, Item 
from .forms import SignupForm 

def index(request):
    items= Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request,'core/index.html', {
        'categories':categories,
        'items':items,
    })


def contact (request):
    return render (request, 'core/contact.html')

def signup(request):
    if request.method =='POST':
        form=SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:    
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form':form
    }) 

def logout_user(request):
    logout(request)
    
    return redirect('/')

def aboutus (request):
    return render (request, 'core/aboutus.html')

def privacypolicy (request):
    return render (request, 'core/privacypolicy.html')       
    

core/templates/core/aboutus.html
{% extends 'core/base.html' %}


{% block title %} Про нас  {% endblock %}

{% block content %}
    <p1 class="mb-12 text-xl text-gray-500  font-semibold "> Ми торгова платформа, де кожен бажаючий може продати або купити необхідний одяг для своїх діток ....<br>Тут ви можете додавати оголошення про продаж дитячих речей.Такой можна зв'язатися з продавцем товару, який вас цікавить.<br> Все швидко,якісно та зручно !!!</p1>
{% endblock %} 

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset=utf-8>
        <meta name="viewport" content ="width=device-width, initial - scale =1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        
        
        

        <title>{% block title %} {% endblock %} | МОЯ КРАМНИЧКА</title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href ="/" class="text-xl font-semibold "> Головна сторінка</a>
            <h1 class="px-6 py-3 text-3xl"><strong> МОЯ КРАМНИЧКА</strong></h1>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Створити</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Каталог</a>


                
                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text- white rounded-xl hover:bg-gray-700">Повідомлення</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text- white rounded-xl hover:bg-gray-700">Мій профіль</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-orange-400 text- white rounded-xl hover:bg-gray-700">Вийти</a>
                {% else %}

                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text- white rounded-xl hover:bg-gray-700">Зареєструватися</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text- white rounded-xl hover:bg-gray-700">Ввійти</a>
                {% endif %}      


            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}

        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">Про нас</h3>

                <p class="text-lg text-gray-500">Ми торгова платформа, де кожен бажаючий може продати або купити необхідний одяг для своїх діток ....</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400"> Меню</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:aboutus'%}" class="text-lg text-teal-500 hover:text-teal-700">Про нас</a></li>
                    <li><a href="{% url 'core:contact'%}" class="text-lg text-teal-500 hover:text-teal-700">Контакты</a></li>
                    <li><a href="{% url 'core:privacypolicy'%}" class="text-lg text-teal-500 hover:text-teal-700">Політика конфіденційності</a></li>
                </ul>


            </div>
        </footer>
    </body>

</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %} Контакти {% endblock %}

{% block content %}
    <h1>Контакти: <br> Вайбер +38(095)-322-86-78 <br> email: molin2@ukr.net</h1>
{% endblock %}    

core/templates/core/index.html
{% extends 'core/base.html' %}


{% block title %} Вітаємо {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded xl" >
        <h2 class="mb-12 text-2xl text-center"> Новинки товару</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{item.image.url}}" class="rounded-t-xl ">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Вартість:{{ item.price }} грн.</p>
                    </div>
                </a> 
            </div>
            {% endfor%}           

        </div>
    </div> 

    
  
{% endblock %}    

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl"> 
    <h1 class="mb-6 text-3xl">Ввійти</h1>

    <form method="post" action=".">
        {% csrf_token %}

        

        <div class="mb-3">
            <label class="inline-block mb-2"> Логін</label><br>
            {{ form.username}}
        </div> 
        
        <div class="mb-3">
            <label class="inline-block mb-2"> Пароль</label><br>
            {{ form.password}}
        </div> 
           

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors}}
                {% endfor %} 
                
                {{form.non_field_errors }}
            </div>
        {% endif %}   

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Прийняти </button>
    </form>
</div>
{% endblock %}

core/templates/core/privacypolicy.html
{% extends 'core/base.html' %}


{% block title %} Політика конфіденційності {% endblock %}

{% block content %}
    
    <h1>ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ ИНФОРМАЦИИ</h1>
    <h2>1. ОБЩИЕ ПОЛОЖЕНИЯ</h2>
    <p>1.1. Термины, используемые в Политике конфиденциальности информации:
        Политика конфиденциальности информации (далее – Политика конфиденциальности) – общие правила, которыми регламентируется сбор, обработка, использование и защита персональных данных, которые могут быть запрошены/получены при использовании Интернет-магазина  <br>
        «Администрация сайта Интернет – магазина (далее – Администрация сайта)» – субъекты уполномочены на управление сайтом, которые организуют и (или) осуществляют обработку персональных данных, а также определяют цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые по персональным данным.<br>
        Персональные данные – сведения или совокупность сведений о физическом лице, которое идентифицировано или может быть конкретно идентифицировано.<br>
        «Обработка персональных данных» – любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных.<br>
        «Конфиденциальность персональных данных» обязательна для соблюдения Оператором или другими лицами, получившими доступ к персональным данным лица, требование не допускать их распространения без согласия субъекта персональных данных или без наличия другого законного основания.<br>
        «Пользователь сайта Интернет – магазина (далее Пользователь)» – лицо, имеющее доступ к Сайту с помощью сети Интернет и использующее Сайт интернет – магазина.<br>
        «Cookies» – небольшой фрагмент данных, отправленный веб-сервером, хранящимся на компьютере пользователя, который веб-клиент или веб-браузер каждый раз пересылает веб-серверу в HTTP-запросе при попытке открыть страницу соответствующего сайта.<br>
        IP-адрес – уникальный сетевой адрес узла в компьютерной сети, построенной по протоколу IP.<br>
        «Третье лицо» – любое лицо, за исключением субъекта персональных данных, владельца или распорядителя персональных данных</p>
    </p>
{% endblock %}  

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl"> 
    <h1 class="mb-6 text-3xl">Зареєструватися"</h1>

    <form method="post" action=".">
        {% csrf_token %}

        

        <div class="mb-3">
            <label class="inline-block mb-2"> Логін</label><br>
            {{ form.username}}
        </div> 
        
        <div class="mb-3">
            <label class="inline-block mb-2"> Email</label><br>
            {{ form.email}}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2"> Пароль</label><br>
            {{ form.password1}}
        </div> 
        
        <div class="mb-3">
            <label class="inline-block mb-2"> Повторити пароль</label><br>
            {{ form.password2}}
        </div>    

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors}}
                {% endfor %} 
                
                {{form.non_field_errors }}
            </div>
        {% endif %}   

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Прийняти </button>
    </form>
</div>
{% endblock %}